### ISSUE TITLE
When fewer Items are used it basicly uses that item to a insane amount

### ISSUE THREAD

**Issue by askusbloodfist** [DerDorius/ItemRumbleMelodyManiaMod#5]
When fewer Items are used it basicly uses that item to a insane amount, It needs to be adjusted to an better amount amount the times it spawns should be mutch less as default. Allso why are you rewarded when not completing a full note?

**Comment by DariusRDev** [comment]
Currently, every note longer than 200 milliseconds has a 25% chance of spawning an item. The spawn rate of items is based on the following table:
![image](https://github.com/DerDorius/ItemRumbleMelodyManiaMod/assets/77979816/fc05f889-1534-4439-8b71-c3aa99bdc1fd)

This ensures that people in last place receive better items to help them catch up.

In the future, I might make the overall spawn rate, which is currently set at 25%, configurable in the options.

**Comment by DariusRDev** [comment]
Perhaps I could convert this Excel sheet into a .csv file, enabling it to be read at runtime. This way, people without development skills could edit the probabilities.

By the way, I'm still working on the balancing. I haven't had a chance yet to test it with friends. 😄

**Comment by DariusRDev** [comment]
>  Allso why are you rewarded when not completing a full note?

Made a new issue #8

**Comment by DariusRDev** [comment]
@askusbloodfist 
Thanks for your feedback :D 

I added these options to manage spawn probabilities:
![image](https://github.com/DerDorius/ItemRumbleMelodyManiaMod/assets/77979816/6d0d3983-7493-4d9b-8e07-af24278cbf7f)
