### ISSUE TITLE
Hide notes Item Should be against the other player?

### ISSUE THREAD

**Issue by askusbloodfist** [DerDorius/ItemRumbleMelodyManiaMod#7]
Would it not be better to have it against the other player? And i think like all other post i made that the number of times it spawns should be mutch less as default. Allso why are you rewarded when not completing a full note?

**Comment by DariusRDev** [comment]
Good point. 
Could also only effect players with more points then the collecting player. In case the collecting player is first place it could effect him.

Will look into this.
